import Head from 'next/head';
import { Inter } from 'next/font/google';
import BlogPost from '@/Components/BlogPosts/BlogPost'
import Header from '@/Components/Header/Header';
import { useState } from 'react';
import HomeBanner from '@/Components/HomeBanner/HomeBanner';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [show2, setShow2] = useState(false);
  const [show, setShow] = useState(false);
  const props = {
    show2, setShow2, show, setShow
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header props={props} />
        <HomeBanner props={props} />
        <BlogPost />
      </>
    </>
  )
}
